# Credit Card Fraud Detection

In [129]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [130]:
data=pd.read_csv('creditcard.csv')

In [131]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [132]:
data.shape

(284807, 31)

In [133]:
data.isnull().values.any()

False

In [134]:
fraud = data[data['Class'] == 1] 
valid = data[data['Class'] == 0] 
outlierFraction = len(fraud)/float(len(valid)) 
print(outlierFraction) 
print('Fraud Cases: {}'.format(len(data[data['Class'] == 1]))) 
print('Valid Transactions: {}'.format(len(data[data['Class'] == 0]))) 

0.0017304750013189597
Fraud Cases: 492
Valid Transactions: 284315


In [135]:
from sklearn.preprocessing import StandardScaler

In [136]:
feature=StandardScaler()

In [138]:
data['normalized Amt']=feature.fit_transform(data['Amount'].values.reshape(-1,1))

In [139]:
data=data.drop(['Amount'],axis=1)

In [140]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V22       V23       V24       V25       V26  \
0  0.098698  0.363787  ...  0.277838 -0.110474  0.066928  0.128539 -0.189115   
1  0.085102 -0.255425  ... -0.638672  0.101288 -0.339846  0.167170  0.125895   
2  0.247676 -1.514654  ...  0.771679  0.909412 -0.689281 -0.327642 -0.139097   
3  0.377436 -1.387024  ...  0.005274 -0.190321 -1.175575  0.647376 -0.221929   
4 -0.270533  0.817739  ...  0.798278 -0.137458  0.141267 -0.206010  0.502292   

        V27       V28  Class  noramlized Amt  normalized Amt  
0  0.133558 -0.021053      0        0.244964        0.244964  
1 -0.008983  0.014724      0       -0.342475       -0.342475  
2 -0.055353 -0.059752      0        1.160686        1.160686  
3  0.062723  0.061458      0        0.140534        0.140534  
4  0.219422  0.215153      0       -0.073403       -0.073403  

[5 rows x 32 columns]

In [141]:
x = data.iloc[:, data.columns != 'Class']
y = data.iloc[:, data.columns == 'Class']


In [142]:
y.head()

Class
0      0
1      0
2      0
3      0
4      0

In [143]:
Fraud = data[data['Class']==1]
Normal = data[data['Class']==0]


In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state=0)


# Applying Random Forest

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score

In [19]:
classifier = RandomForestClassifier(random_state = 0, n_estimators = 100,criterion = 'entropy')

In [20]:
classifier.fit(x_train, y_train)

C:\Users\KIIT\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [21]:
y_pred = classifier.predict(x_test)
acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)


In [22]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [23]:
acc

0.9995318516437859

In [24]:
prec

0.9572649572649573

In [25]:
rec

0.7619047619047619

In [26]:
f1

0.8484848484848485

In [27]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [28]:
cm

array([[85291,     5],
       [   35,   112]], dtype=int64)

In [45]:
test=[[4,0.687,0.21,0.224,0.3242,0.32424,0.554,0.2334,0.245,0.7688,0.366,0.67878,0.356,0.676,0.35465,0.667,0.465,0.3545,0.657,0.5667,0.35467,0.34567,0.576,0.87654,0.3456,0.7643,0.345,0.765,0.3456,3.5666]]

In [46]:
classifier.predict(test)

array([0], dtype=int64)

# Applying svm

In [39]:
from sklearn.svm import SVC

In [118]:
sv = SVC(kernel='rbf',C=0.0001)

In [119]:
sv.fit(x_train,y_train)

C:\Users\KIIT\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=0.0001, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [120]:
sv.score(x_train,y_train)

0.9982694970004614

In [121]:
sv.score(x_test,y_test)

0.9982795547909132

In [122]:
sv_pred=sv.predict(x_test)
sv_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [123]:
accuracy_score(y_test,sv_pred)

0.9982795547909132

In [124]:
cm1 = confusion_matrix(y_test, sv_pred) 
cm1

array([[85296,     0],
       [  147,     0]], dtype=int64)

In [147]:
test=[[4,0.687,0.2433,0.57,0.224,0.3242,0.32424,0.554,0.2334,0.245,0.7688,0.366,0.5790,0.67878,0.35465,0.667,0.465,0.3545,0.657,0.5667,0.35467,0.34567,0.576,0.87654,0.3456,0.7643,0.345,0.765,0.3456,3.5666]]

In [148]:
sv.predict(test)

array([0], dtype=int64)

# Applying Logistic Regression



In [77]:
from sklearn.linear_model import LogisticRegression

In [78]:
p1=LogisticRegression()

In [79]:
p1.fit(x_train,y_train)

C:\Users\KIIT\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\KIIT\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [80]:
pred=p1.predict(x_test)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [81]:
p1.score(x_train,y_train)

0.9989767460524468

In [82]:
p1.score(x_test,y_test)

0.9989817773252344

In [95]:
accuracy_score(y_test,pred)

0.9989817773252344

In [83]:
recall_score(y_test,pred)

0.6666666666666666

In [84]:
from sklearn.metrics import confusion_matrix

In [85]:
cm2=confusion_matrix(y_test,pred)
cm2

array([[85258,    38],
       [   49,    98]], dtype=int64)

In [89]:
test=[[4,0.687,0.2433,0.57,0.224,0.3242,0.32424,0.554,0.2334,0.245,0.7688,0.366,0.5790,0.67878,0.35465,0.667,0.465,0.3545,0.657,0.5667,0.35467,0.34567,0.576,0.87654,0.3456,0.7643,0.345,0.765,0.3456,3.5666]]

In [90]:
p1.predict(test)

array([0], dtype=int64)